### ISSUE TITLE
incorrect header check: Django/Docker

### ISSUE THREAD

**Issue by iulianbeleiu** [Anyline/anyline-ocr-anylinejs-module#5]
Hi, I am experiencing some issue while trying to test it inside a Docker with Django. It's just loading but the scan does not start.
Problem:
```
anyline.js:16 onCutoutListUpdate does not have any registered listeners. Publish cancelled.
setAnylineLoading does not have any registered listeners. Publish cancelled.
animation NONE not found!
animation NONE not found!
failed to asynchronously prepare wasm: incorrect header check
incorrect header check
Uncaught (in promise) RuntimeError: abort(incorrect header check) at Error
```
#### Request:
```
Request URL: http://127.0.0.1/frontend/anyline/anylinejs/anylinejs.js
Request Method: GET
Status Code: 200 OK (from disk cache)
Remote Address: 127.0.0.1:80
Referrer Policy: no-referrer-when-downgrade
```

#### Request Response:
```
Content-Disposition: inline; filename="anylinejs.js"
Content-Length: 1142742
Content-Type: application/javascript
Date: Thu, 11 Jun 2020 18:56:31 GMT
Last-Modified: Thu, 11 Jun 2020 18:49:07 GMT
Server: WSGIServer/0.2 CPython/3.8.3
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
```
#### Request Headers:
```
Referer: http://127.0.0.1/frontend/scan.html
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
```

Any idea what the problem could be?
Another thing: Would it be possible to use it on localhost from mobile on the same network? I have my localhost and I try to reach it from my mobile phone using laptop's ip with the format 192.168.100.** Currently if I try to access it nothing happens.
Thank you very much!

**Comment by davlhd** [comment]
Hello,

localhost and 127.0.0.1 can only be used from the local machine. I created a license for 192.168.100.10 for you to try:

eyAiZGVidWdSZXBvcnRpbmciOiAib24iLCAiaW1hZ2VSZXBvcnRDYWNoaW5nIjogZmFsc2UsICJqc0lkZW50aWZpZXIiOiBbICIxOTIuMTY4LjEwMC4xMCIgXSwgImxpY2Vuc2VLZXlWZXJzaW9uIjogMiwgIm1ham9yVmVyc2lvbiI6ICIyMCIsICJtYXhEYXlzTm90UmVwb3J0ZWQiOiAwLCAicGluZ1JlcG9ydGluZyI6IHRydWUsICJwbGF0Zm9ybSI6IFsgIkpTIiBdLCAic2NvcGUiOiBbICJBTEwiIF0sICJzaG93UG9wVXBBZnRlckV4cGlyeSI6IGZhbHNlLCAic2hvd1dhdGVybWFyayI6IGZhbHNlLCAidG9sZXJhbmNlRGF5cyI6IDAsICJ2YWxpZCI6ICIyMDIwLTA3LTMwIiB9Ck9ndGhxSGEyYnU4Y24zRHhlNEFzNWtXZUI1NlRUbXh4VVBLZVVFbmYwS05EME1nK3NHZWZLZDdFOTRDWkNPbW4KOGZHQkU1VHEwdnhHYWRTYitCbm5EQUxsVXp1UGZrTWJ5a0ZPeGVhVm8xZnRUYzNzWjdTSmorVWRmSUVvRXp6KwpSS0tBS0ZSZ3hWZWMrME8rTjJpSldpWE16ZFM4ZDErMnRtMEphRXpYNW9ONnQyR05LMDNLNmR2UEdneHl2NmhtClc1S3QrYW1GN2Rlb0s3c0pVM3ZQUXpycDdRT09vR2l5dk11aTQ3UEFlRzllZnZHVlpPYzMvV1Vpcnl6VnQzLzMKWkVJbHczMXFObUZ6M2NObnl0NnNZa0dWcWxIUVhrL0tET08yclNob2padnJBbnJXUFN0MzBQYWRSN2lYdG5FUwpuWWhTcTA3aTFVSkU5cW5Bem1oVEFBPT0K

Can you provide more details about your docker setup? 

You can create a simple python server using something like this:

```
import BaseHTTPServer, SimpleHTTPServer
import ssl
import os
httpd = BaseHTTPServer.HTTPServer(('192.168.100.10', 4443),
        SimpleHTTPServer.SimpleHTTPRequestHandler)

httpd.socket = ssl.wrap_socket (httpd.socket, 
        keyfile="server.key", 
        certfile='server.crt', server_side=True)

web_dir = os.path.join(os.path.dirname(__file__), './www')
os.chdir(web_dir)

httpd.serve_forever()
```

Please note that you **have to** use https for AnylineJS to work because webcam access is required. For this examples to work you can create a self-signed certificate.

We plan on providing a demo server with the github example in the future. It's just not ready yet.
